name: Android CI

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install node modules
        run: npx yarn install

      - name: Install old NDK
        run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT}

      - name: Pack app
        run: npm run android:build:dev

      - name: Upload apk to artifacts
        uses: actions/upload-artifact@v1
        if: github.ref == 'refs/heads/develop'
        with:
          name: edu.rise.ihnilatis.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

      - name: Upload artifact to App Center
        uses: wzieba/AppCenter-Github-Action@v1.0.0
        if: github.ref == 'refs/heads/master'
        with:
          appName: CovTracer/Android-Debug-CI
          token: ${{ secrets.APP_CENTER_TOKEN }}
          group: Collaborators
          file: android/app/build/outputs/apk/debug/app-debug.apk
