name: Android CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install node modules
          run: npm ci

      - name: Bundle app
          run: npm run android:bundle

      - name: Pack app
          run: npm run android:build:dev

      - name: Upload apk
        uses: actions/upload-artifact@v1
        with:
          name: edu.rise.ihnilatis.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
